package com.example.tail.ui.map

import android.content.Context
import android.util.Log
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import org.json.JSONObject
import java.io.File
import java.net.HttpURLConnection
import java.net.URL

private const val TAG = "CountryFacts"
private const val ASSET_PATH = "country_facts.json"
private const val ALIAS_PATH = "country_name_aliases.json"
private const val OVERRIDES_FILE = "country_population_overrides.json"
private const val REST_COUNTRIES_URL =
    "https://restcountries.com/v3.1/all?fields=name,population"

/**
 * Static per-country facts for the map screen's country section: local words
 * for hello / thank you (with English pronunciation), founding year and an
 * approximate population. Data lives in app/src/main/assets/country_facts.json
 * (generated by scripts/gen_country_facts.py), keyed by Natural Earth 110m
 * country names so it matches the map's country detection directly.
 *
 * Population numbers can be refreshed at runtime via [updatePopulations]
 * (REST Countries API); overrides are persisted in app files and merged over
 * the bundled asset on every load.
 */
object CountryFacts {

    data class Fact(
        val hello: String,
        val helloPron: String,
        val thanks: String,
        val thanksPron: String,
        val founded: String,
        val population: Long,
        val popYear: Int,
        /** Dominant local language tag (e.g. "it", "ja") for TTS playback. */
        val lang: String = "en"
    )

    @Volatile private var cache: Map<String, Fact>? = null
    @Volatile private var flagsCache: Map<String, String>? = null

    /** Loads + caches all facts, merging any saved population overrides. */
    fun load(context: Context): Map<String, Fact> {
        cache?.let { return it }
        return synchronized(this) {
            cache ?: parse(context).also { cache = it }
        }
    }

    /** Drops the cache so the next [load] re-reads overrides (post-update). */
    fun invalidate() {
        synchronized(this) {
            cache = null
        }
    }

    /**
     * NE country name → ISO-3166 alpha-2 code (e.g. "Slovenia" → "SI"),
     * from assets/country_flags.json. Used to build emoji flags.
     */
    fun loadFlags(context: Context): Map<String, String> {
        flagsCache?.let { return it }
        return synchronized(this) {
            flagsCache ?: run {
                val out = HashMap<String, String>(200)
                try {
                    val text = context.assets.open("country_flags.json")
                        .bufferedReader().use { it.readText() }
                    val root = JSONObject(text)
                    for (name in root.keys()) out[name] = root.getString(name)
                } catch (e: Exception) {
                    Log.w(TAG, "Failed to load country_flags.json: ${e.message}")
                }
                out.also { flagsCache = it }
            }
        }
    }

    private fun parse(context: Context): Map<String, Fact> {
        val out = HashMap<String, Fact>(200)
        try {
            val text = context.assets.open(ASSET_PATH).bufferedReader().use { it.readText() }
            val root = JSONObject(text)
            for (name in root.keys()) {
                val o = root.getJSONObject(name)
                out[name] = Fact(
                    hello = o.getString("h"),
                    helloPron = o.getString("hp"),
                    thanks = o.getString("t"),
                    thanksPron = o.getString("tp"),
                    founded = o.optString("f"),
                    population = o.optLong("p"),
                    popYear = o.optInt("py"),
                    lang = o.optString("l", "en")
                )
            }
        } catch (e: Exception) {
            Log.w(TAG, "Failed to load $ASSET_PATH: ${e.message}")
        }
        // Merge saved population overrides {name: [pop, year]}.
        try {
            val file = File(context.filesDir, OVERRIDES_FILE)
            if (file.exists()) {
                val overrides = JSONObject(file.readText())
                for (name in overrides.keys()) {
                    val arr = overrides.getJSONArray(name)
                    out[name]?.let {
                        out[name] = it.copy(population = arr.getLong(0), popYear = arr.getInt(1))
                    }
                }
            }
        } catch (e: Exception) {
            Log.w(TAG, "Failed to load overrides: ${e.message}")
        }
        return out
    }

    /**
     * Fetches current populations from restcountries.com and stores them as
     * overrides. Returns the number of countries updated, or -1 on failure.
     * Must be called from a background dispatcher (it performs network IO).
     */
    suspend fun updatePopulations(context: Context): Int =
        withContext(Dispatchers.IO) {
            try {
                val conn = URL(REST_COUNTRIES_URL).openConnection() as HttpURLConnection
                conn.connectTimeout = 10000
                conn.readTimeout = 15000
                val body = conn.inputStream.bufferedReader().use { it.readText() }
                val countries = org.json.JSONArray(body)
                val aliases = loadAliases(context)
                val overridesFile = File(context.filesDir, OVERRIDES_FILE)
                val existing = if (overridesFile.exists()) {
                    JSONObject(overridesFile.readText())
                } else JSONObject()
                val year = java.time.Year.now().value
                var count = 0
                for (i in 0 until countries.length()) {
                    val c = countries.getJSONObject(i)
                    val common = c.getJSONObject("name").optString("common") ?: continue
                    val neName = aliases[common] ?: common
                    if (!existing.has(neName)) {
                        // Only refresh countries we actually know about.
                        if (!load(context).containsKey(neName)) continue
                    }
                    val pop = c.optLong("population", -1L)
                    if (pop <= 0) continue
                    existing.put(neName, org.json.JSONArray().put(pop).put(year))
                    count++
                }
                if (count > 0) overridesFile.writeText(existing.toString())
                invalidate()
                count
            } catch (e: Exception) {
                Log.w(TAG, "Population update failed: ${e.message}")
                -1
            }
        }

    private fun loadAliases(context: Context): Map<String, String> {
        return try {
            val text = context.assets.open(ALIAS_PATH).bufferedReader().use { it.readText() }
            val root = JSONObject(text)
            val out = HashMap<String, String>(root.length())
            for (k in root.keys()) out[k] = root.getString(k)
            out
        } catch (e: Exception) {
            emptyMap()
        }
    }
}
